### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by kungpaogao** [n2n-milstein/inventory#13]
Only small considerations were made to the design in the initial development

- we should come up with a set color scheme - not the default Vuetify layout
- "Approvals" dropdown in sidebar is confusing

**Comment by kungpaogao** [comment]
- add an archive link in the sidebar

**Comment by kira-segenchuk** [comment]
If something looks bad (design wise) discuss then fix

**Comment by kungpaogao** [comment]
Not specific enough.
