### ISSUE TITLE
Customizable headers for inventory table

### ISSUE THREAD

**Issue by kungpaogao** [n2n-milstein/inventory#17]
Create a settings page for users to modify which headers should be displayed in the inventory table - will need to decide if this should be global or just for a single login

**Comment by kira-segenchuk** [comment]
- click button in corner, 
- pop up (or drop down menu) shows available headers. have check boxes to indicate if header is chosen

**Comment by kungpaogao** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/11168401/74091689-136ade80-4a88-11ea-8415-7958f57279a7.png">

**Comment by kungpaogao** [comment]
Define the headers based on usage and user testing as opposed to allowing on-the-fly editing.
