### ISSUE TITLE
Implement some sort of state for undos

### ISSUE THREAD

**Issue by kungpaogao** [n2n-milstein/inventory#18]
This is a long shot, but it would be cool if we could keep track of state in our database. This would allow:

- show recent changes
- undo operations

**Comment by kira-segenchuk** [comment]
- other possibility: have a "are you sure you want to do this" pop up for important actions (like approve or deny)

- to do: ask next time we see them, and implement pop up if this is a concern

why is undo hard? we only write to one table, hard to know what item you want an action undone on. On;y way to fix is have somewhere to temporarily store.

**Comment by kungpaogao** [comment]
A solution for undo at the individual document level is updating how we store the document. It could be a document with a collection of timestamps. Under normal conditions, it just displays the latest version, but it's possible to "time travel."
```
inventory
   |___ <furniture id>
                   |___ <timestamp 3> --> Furniture document
                   |___ <timestamp 2> --> Furniture document
                   |___ <timestamp 1> --> Furniture document
```

**Comment by kungpaogao** [comment]
I'm closing this because I don't think this is important or worth the struggle. Having confirmation dialogs throughout will be helpful and achieve a similar idea.
