### ISSUE TITLE
Make attributes less ambiguous

### ISSUE THREAD

**Issue by kungpaogao** [n2n-milstein/inventory#20]
We can choose whether or not we want to keep the "X" symbol next to the negative attributes. But regardless, we should add a "not" in front to make it less ambiguous.

**Comment by kira-segenchuk** [comment]
- remove x and check mark, replace with thumbs up and thumbs down
- have one output for the positive option, one for the negative option

**Comment by kungpaogao** [comment]
Fixed by #37
