### ISSUE TITLE
Inventory View - filters

### ISSUE THREAD

**Issue by kungpaogao** [n2n-milstein/inventory#9]
Need some sort of filter bar w/ buttons (see Airbnb) or something similar to filter out what is visible in the inventory table

**Comment by crencricca** [comment]
**MINIMUM VIABLE PRODUCT**
Allow for all combinations of the following filters to be applied to the inventory data table:
- Class
- Status
- Date Added

**GOAL**
Allow for all combinations of any number of filters (once a list is finalized). This should be built in a way that can be relatively easy to modify. 
_Stretch Goal: UI-based modification_

**TODO**
- Filtering by date + implementing date picker
- Rework current code to be more adaptable with class and status
- Allow filters to be cleared individually

**TEST**
- All combinations of filters
- Clearing filters
- Add more items to inventory and test with all value possibilities in each category

**Comment by crencricca** [comment]
@kira-segenchuk Could you take a look at how we could get a date picker working as a filter?

**Comment by kungpaogao** [comment]
This will probably be useful: https://vuetifyjs.com/en/components/date-pickers/#date-month-pickers
